language: node_js
node_js:
  - "12"
dist: trusty
cache: npm

#script:
#  - npm run test
##  - npm run build:ui
#
#
#jobs:
#  include:
#    - stage: npm release
#      if: tag is present
#      node_js:
#        - "12"
#      script:
#        - npm run build:ui
#      deploy:
#        provider: npm
#        email: "$NPM_EMAL"
#        api_key: "$NPM_TOKEN"
#        skip_cleanup: true
#        on:
#          tags: true
